### ISSUE TITLE
expected dtype object, got 'numpy.dtype[float64]', when following getting started

### ISSUE THREAD

**Issue by Max1461** [TurtleTools/geometricus#22]
When I`m doing the Moment invariants calculation step from the getting started page(after having done the previous steps), using the following code:

```
invariants_kmer = []
invariants_radius = []

start_time = time()
for i, key in enumerate(X_names):
    if i > 0 and i % 50 == 0:
        print(f"{i} proteins in {(time() - start_time):.2f} seconds")
    invariants_kmer.append(MomentInvariants.from_prody_atomgroup(key, pdbs[i], split_type=SplitType.KMER, split_size=16))
    invariants_radius.append(MomentInvariants.from_prody_atomgroup(key, pdbs[i], split_type=SplitType.RADIUS, split_size=10))
```
I run into the following error:
TypeError: expected dtype object, got 'numpy.dtype[float64]'

This kind of error might be caused by a mismatch between numpy and numba, so I updated both of these to the, at the moment of writing, newest versions of 1.21.5 for Numpy and 0.50.1 for numba. But This still resulted in the same error while executing the code.

Is there anything I am missing that might resolve the problem?

Thanks in advance and with kind regards,

Max

**Comment by akdel** [comment]
The issue should be fixed now with [this commit](https://github.com/TurtleTools/geometricus/commit/d38ebd12fcf0409e12cfdb4bc2cf5f9e2f30cc91). I froze the versions of the latest compatible numba and numpy.  Let me know if the problem persists and I'll reopen the issue. The fix will not apply to the pypi version of geometricus but installing with `pip install git+https://github.com/TurtleTools/geometricus.git` should work.
